import { useEffect,useMemo,useRef,useState } from 'react';
import type { MazeGraph } from '../../maze/graph';
import type { HistoryMazeParams,PlayHistoryEntry } from '../history';
import { COMPETITION_LAST_ROOM_PREFIX,COMPETITION_ROOM_STORAGE_PREFIX,decodeSignal,encodeSignal,mergeRoomResults,parseRoomResult,parseStoredRoom,resultFromAttempt,roomResultsCsv,type RoomResult } from '../competitionRoom';
import { signalQrDataUrl } from '../signalQr';

type Props={mazeId:string;maze:HistoryMazeParams;graph:MazeGraph;entries:readonly PlayHistoryEntry[];onOpenMaze:(maze:HistoryMazeParams)=>void};
type BarcodeDetectorLike={detect:(source:ImageBitmapSource)=>Promise<readonly {rawValue:string}[]>};
type Role='idle'|'host'|'guest';
const ICE_SERVERS:RTCConfiguration={iceServers:[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302']}],iceCandidatePoolSize:4};
const duration=(ms:number)=>{const tenths=Math.floor(ms/100),seconds=Math.floor(tenths/10);return`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}.${tenths%10}`;};
const waitForIce=(peer:RTCPeerConnection)=>peer.iceGatheringState==='complete'?Promise.resolve(true):new Promise<boolean>(resolve=>{let timer=0;const finish=(complete:boolean)=>{peer.removeEventListener('icegatheringstatechange',done);window.clearTimeout(timer);resolve(complete);};const done=()=>{if(peer.iceGatheringState==='complete')finish(true);};peer.addEventListener('icegatheringstatechange',done);timer=window.setTimeout(()=>finish(false),10000);});
const download=(name:string,type:string,content:string)=>{const url=URL.createObjectURL(new Blob([content],{type})),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url);};

function SignalQR({value,label}:{value:string;label:string}){
  const [source,setSource]=useState(''),[failed,setFailed]=useState(false);
  useEffect(()=>{let active=true;setFailed(false);signalQrDataUrl(value).then(url=>{if(active)setSource(url);}).catch(()=>{if(active)setFailed(true);});return()=>{active=false;};},[value]);
  return failed?<p className="muted">This connection code is too large for a reliable QR image. Use Copy instead.</p>:source?<figure className="signal-qr"><img src={source} alt={`${label} QR code`}/><figcaption>Scan on the other device, then paste the decoded connection code.</figcaption><a className="btn btn-sm" href={source} download={`infimaze-${label.toLowerCase().replace(/\s+/g,'-')}.svg`}>Save QR</a></figure>:<p role="status" className="muted">Creating QR code…</p>;
}

export default function CompetitionRoom({mazeId,maze,graph,entries,onOpenMaze}:Props){
  const restoredRoom=useMemo(()=>{try{return localStorage.getItem(`${COMPETITION_LAST_ROOM_PREFIX}${mazeId}`)??'';}catch{return'';}},[mazeId]);
  const [role,setRole]=useState<Role>('idle'),[roomId,setRoomId]=useState(restoredRoom),[player,setPlayer]=useState('Player');
  const [offer,setOffer]=useState(''),[answer,setAnswer]=useState(''),[remoteCode,setRemoteCode]=useState('');
  const [busy,setBusy]=useState<'offer'|'join'|'answer'|null>(null);
  const restoredResults=useMemo(()=>{try{return restoredRoom?parseStoredRoom(localStorage.getItem(`${COMPETITION_ROOM_STORAGE_PREFIX}${restoredRoom}`),mazeId,graph):[];}catch{return[];}},[restoredRoom,mazeId,graph]);
  const [status,setStatus]=useState(restoredResults.length?'Saved standings restored. Start or join a room to reconnect.':'No room connected.'),[error,setError]=useState<string|null>(null),[peerCount,setPeerCount]=useState(0);
  const [results,setResults]=useState<RoomResult[]>(restoredResults),resultsRef=useRef<RoomResult[]>(restoredResults);
  const peers=useRef(new Set<RTCPeerConnection>()),channels=useRef(new Set<RTCDataChannel>()),pendingHost=useRef<RTCPeerConnection|null>(null);
  const best=useMemo(()=>entries.filter(entry=>entry.mazeId===mazeId&&entry.status==='completed'&&(entry.hints??0)===0).sort((a,b)=>a.elapsedMs-b.elapsedMs||a.moves-b.moves)[0],[entries,mazeId]);
  const importedOffer=useMemo(()=>{try{return decodeSignal(remoteCode,'offer');}catch{return null;}},[remoteCode]);
  const needsHostMaze=role==='idle'&&importedOffer!==null&&importedOffer.mazeId!==mazeId;
  const sharedMaze=useMemo(()=>({...maze,startIcon:/^data:/i.test(maze.startIcon??'')?null:maze.startIcon,goalIcon:/^data:/i.test(maze.goalIcon??'')?null:maze.goalIcon}),[maze]);
  useEffect(()=>{resultsRef.current=results;if(roomId)try{localStorage.setItem(`${COMPETITION_ROOM_STORAGE_PREFIX}${roomId}`,JSON.stringify(results));localStorage.setItem(`${COMPETITION_LAST_ROOM_PREFIX}${mazeId}`,roomId);}catch{}},[results,roomId,mazeId]);
  useEffect(()=>()=>{for(const channel of channels.current)channel.close();for(const peer of peers.current)peer.close();},[]);

  const accept=(incoming:unknown[])=>{
    const valid=incoming.flatMap(value=>{try{return[parseRoomResult(value,mazeId,graph)];}catch{return[];}});
    if(!valid.length&&incoming.length)throw new Error('The peer sent no valid results for this maze.');
    const merged=mergeRoomResults(resultsRef.current,valid);resultsRef.current=merged;setResults(merged);return merged;
  };
  const broadcast=(value:unknown,except?:RTCDataChannel)=>{const message=JSON.stringify(value);for(const channel of channels.current)if(channel!==except&&channel.readyState==='open')channel.send(message);};
  const wireChannel=(channel:RTCDataChannel,isHost:boolean)=>{
    channels.current.add(channel);
    channel.addEventListener('open',()=>{setPeerCount([...channels.current].filter(item=>item.readyState==='open').length);setStatus('Connected directly. Results stay on participating devices.');channel.send(JSON.stringify({type:'snapshot',mazeId,results:resultsRef.current}));});
    channel.addEventListener('close',()=>{channels.current.delete(channel);setPeerCount([...channels.current].filter(item=>item.readyState==='open').length);setStatus('A peer disconnected. Saved room standings remain available.');});
    channel.addEventListener('message',event=>{try{const message:unknown=JSON.parse(String(event.data));if(!message||typeof message!=='object')throw new Error();const data=message as {type?:unknown;mazeId?:unknown;results?:unknown};if(data.mazeId!==mazeId||!Array.isArray(data.results))throw new Error('The peer is using a different maze.');const merged=accept(data.results);if(isHost)broadcast({type:'snapshot',mazeId,results:merged},channel);}catch(reason){setError(reason instanceof Error?reason.message:'Could not read the peer message.');}});
  };
  const wirePeer=(peer:RTCPeerConnection)=>{peers.current.add(peer);peer.addEventListener('connectionstatechange',()=>{if(peer.connectionState==='failed'){setError('Direct connection failed. This network may require a TURN relay, which this zero-cost room does not use.');setStatus('Connection failed.');}if(['closed','disconnected'].includes(peer.connectionState))peers.current.delete(peer);});return peer;};
  const createRoom=()=>{for(const peer of peers.current)peer.close();peers.current.clear();channels.current.clear();const id=crypto.randomUUID();setRoomId(id);setRole('host');setOffer('');setAnswer('');setRemoteCode('');setResults([]);resultsRef.current=[];setPeerCount(0);setError(null);setStatus('Room created. Generate an offer for each participant.');};
  const createOffer=async()=>{try{setBusy('offer');setError(null);setStatus('Gathering direct network addresses…');const peer=wirePeer(new RTCPeerConnection(ICE_SERVERS)),channel=peer.createDataChannel('infimaze-room');wireChannel(channel,true);await peer.setLocalDescription(await peer.createOffer());const complete=await waitForIce(peer);pendingHost.current=peer;setOffer(encodeSignal({version:1,kind:'offer',roomId,mazeId,maze:sharedMaze,description:peer.localDescription!.toJSON()}));setStatus(complete?'Send this offer to one participant, then import their answer.':'STUN timed out. This offer may still work on the same local network.');}catch(reason){setStatus('Could not create a participant offer.');setError(reason instanceof Error?reason.message:'Could not create an offer.');}finally{setBusy(null);}};
  const acceptAnswer=async()=>{try{setBusy('answer');setError(null);if(!pendingHost.current)throw new Error('Generate an offer before importing an answer.');const signal=decodeSignal(remoteCode,'answer');if(signal.roomId!==roomId||signal.mazeId!==mazeId)throw new Error('This answer belongs to a different room or maze.');await pendingHost.current.setRemoteDescription(signal.description);pendingHost.current=null;setRemoteCode('');setOffer('');setStatus('Answer accepted. Establishing the direct data channel…');}catch(reason){setStatus('Could not accept the participant answer.');setError(reason instanceof Error?reason.message:'Could not import the answer.');}finally{setBusy(null);}};
  const joinRoom=async()=>{try{setError(null);const signal=decodeSignal(remoteCode,'offer');if(signal.mazeId!==mazeId){onOpenMaze(signal.maze);setStatus(`Opened the host's ${signal.maze.width}×${signal.maze.height}, seed ${signal.maze.seed} maze. Join when it finishes loading.`);return;}setBusy('join');setStatus('Reading the offer and gathering direct network addresses…');const peer=wirePeer(new RTCPeerConnection(ICE_SERVERS));peer.addEventListener('datachannel',event=>wireChannel(event.channel,false));await peer.setRemoteDescription(signal.description);await peer.setLocalDescription(await peer.createAnswer());const complete=await waitForIce(peer);setRoomId(signal.roomId);setRole('guest');const stored=parseStoredRoom(localStorage.getItem(`${COMPETITION_ROOM_STORAGE_PREFIX}${signal.roomId}`),mazeId,graph);resultsRef.current=stored;setResults(stored);setAnswer(encodeSignal({version:1,kind:'answer',roomId:signal.roomId,mazeId,maze:signal.maze,description:peer.localDescription!.toJSON()}));setRemoteCode('');setStatus(complete?'Return this answer code to the host.':'STUN timed out. Return the answer anyway; it may work on the same local network.');}catch(reason){setStatus('Could not create an answer from that offer.');setError(reason instanceof Error?reason.message:'Could not join the room.');}finally{setBusy(null);}};
  const submitBest=()=>{try{if(!best)throw new Error('Complete this maze without hints before sharing a result.');const result=resultFromAttempt(best,player),merged=accept([result]);broadcast({type:'snapshot',mazeId,results:merged});setStatus(channels.current.size?'Result shared with connected peers.':'Result saved locally; it will be sent when a peer connects.');setError(null);}catch(reason){setError(reason instanceof Error?reason.message:'Could not share the result.');}};
  const copy=async(value:string)=>{try{await navigator.clipboard.writeText(value);setStatus('Connection code copied.');}catch{setError('Could not copy automatically. Select and copy the code manually.');}};
  const shareCode=async(value:string,label:string)=>{try{if(!navigator.share){await copy(value);return;}await navigator.share({title:`InfiMaze ${label}`,text:value});setStatus('Connection code shared.');}catch(reason){if(reason instanceof DOMException&&reason.name==='AbortError')return;setError('Could not open sharing. Copy the code instead.');}};
  const pasteCode=async()=>{try{const value=await navigator.clipboard.readText();if(!value.trim())throw new Error();setRemoteCode(value.trim());setStatus('Connection code pasted.');setError(null);}catch{setError('Clipboard access was unavailable. Paste the code into the field manually.');}};
  const scanCode=async(file:File)=>{try{const Detector=(window as typeof window&{BarcodeDetector?:new(options:{formats:string[]})=>BarcodeDetectorLike}).BarcodeDetector;if(!Detector)throw new Error('QR scanning is unavailable in this browser. Use Paste offer instead.');const bitmap=await createImageBitmap(file);try{const codes=await new Detector({formats:['qr_code']}).detect(bitmap);const value=codes[0]?.rawValue?.trim();if(!value)throw new Error('No QR code was found in that image. Try again with the code filling the frame.');decodeSignal(value,'offer');setRemoteCode(value);setStatus('Host offer scanned.');setError(null);}finally{bitmap.close();}}catch(reason){setError(reason instanceof Error?reason.message:'Could not scan that QR code.');}};
  const cancelOffer=()=>{pendingHost.current?.close();pendingHost.current=null;setOffer('');setRemoteCode('');setStatus('Participant offer cancelled. You can generate a fresh one.');setError(null);};
  const leave=()=>{for(const channel of channels.current)channel.close();for(const peer of peers.current)peer.close();channels.current.clear();peers.current.clear();pendingHost.current=null;setRole('idle');setOffer('');setAnswer('');setPeerCount(0);setStatus('Left the room. Saved standings remain on this device.');};

  return <section className="competition-room" aria-label="Serverless competition room" aria-busy={busy!==null}>
    <div className="history-heading"><strong>Serverless competition room</strong><span className="muted">No account or server</span></div>
    <p className="muted">Connect directly with offer and answer codes. A host offer can open its maze automatically. Restrictive networks may require TURN and cannot connect.</p>
    <label>Player name<input className="input" name="competition-player" maxLength={24} value={player} onChange={event=>setPlayer(event.target.value)}/></label>
    {role==='idle'?<div className="hstack"><button type="button" className="btn btn-primary" onClick={createRoom}>Create room</button><button type="button" className="btn" onClick={joinRoom} disabled={!remoteCode.trim()||busy!==null}>{busy==='join'?'Creating answer…':needsHostMaze?'Open host maze':'Join from offer'}</button></div>:<div className="history-heading"><span>{role==='host'?'Hosting':'Joined'} · {peerCount} connected</span><button type="button" className="btn btn-sm" onClick={leave}>Leave room</button></div>}
    {(role==='idle'||role==='guest')&&<div className="signal-field"><label htmlFor="competition-offer-import">Host offer code</label><textarea id="competition-offer-import" name="competition-offer-import" rows={4} value={remoteCode} onChange={event=>setRemoteCode(event.target.value)} placeholder="Paste the host’s offer code"/><div className="hstack"><button type="button" className="btn btn-sm" onClick={pasteCode}>Paste offer</button><label className="btn btn-sm" htmlFor="competition-offer-scan">Scan QR code</label><input id="competition-offer-scan" className="visually-hidden" type="file" accept="image/*" capture="environment" onChange={event=>{const file=event.target.files?.[0];if(file)void scanCode(file);event.target.value='';}}/></div></div>}
    {role==='host'&&<>
      <button type="button" className="btn" onClick={createOffer} disabled={!!offer||busy!==null}>{busy==='offer'?'Gathering addresses…':'Add participant'}</button>
      {offer&&<div className="signal-field"><label htmlFor="competition-offer">Offer to participant</label><textarea id="competition-offer" name="competition-offer" rows={4} readOnly value={offer}/><SignalQR value={offer} label="Host offer"/><div className="hstack"><button type="button" className="btn btn-sm" onClick={()=>copy(offer)}>Copy offer</button><button type="button" className="btn btn-sm" onClick={()=>shareCode(offer,'host offer')}>Share offer</button><button type="button" className="btn btn-sm" onClick={cancelOffer}>Cancel offer</button></div></div>}
      {offer&&<div className="signal-field"><label htmlFor="competition-answer-import">Participant answer</label><textarea id="competition-answer-import" name="competition-answer-import" rows={4} value={remoteCode} onChange={event=>setRemoteCode(event.target.value)} placeholder="Paste their answer code"/><div className="hstack"><button type="button" className="btn btn-sm" onClick={pasteCode}>Paste answer</button><button type="button" className="btn btn-sm btn-primary" disabled={!remoteCode.trim()||busy!==null} onClick={acceptAnswer}>{busy==='answer'?'Accepting answer…':'Connect participant'}</button></div></div>}
    </>}
    {role==='guest'&&answer&&<div className="signal-field"><label htmlFor="competition-answer">Answer to host</label><textarea id="competition-answer" name="competition-answer" rows={4} readOnly value={answer}/><SignalQR value={answer} label="Guest answer"/><div className="hstack"><button type="button" className="btn btn-sm" onClick={()=>copy(answer)}>Copy answer</button><button type="button" className="btn btn-sm" onClick={()=>shareCode(answer,'guest answer')}>Share answer</button></div></div>}
    <div role="status" className="muted">{status}</div>{error&&<p role="alert" className="shared-error">{error}</p>}
    {role!=='idle'&&<button type="button" className="btn btn-primary" onClick={submitBest} disabled={!best}>Share my best result</button>}
    {!!results.length&&<><div className="leaderboard-scroll"><table aria-label="Room standings"><thead><tr><th>Rank</th><th>Player</th><th>Time</th><th>Moves</th><th>Revisits</th></tr></thead><tbody>{results.map((result,index)=><tr key={result.id}><td>{index+1}</td><td>{result.player}</td><td>{duration(result.elapsedMs)}</td><td>{result.moves}</td><td>{result.revisits}</td></tr>)}</tbody></table></div><div className="hstack"><button type="button" className="btn btn-sm" onClick={()=>download(`infimaze-room-${roomId}.json`,'application/json',JSON.stringify({version:1,roomId,mazeId,results},null,2))}>Export JSON</button><button type="button" className="btn btn-sm" onClick={()=>download(`infimaze-room-${roomId}.csv`,'text/csv',roomResultsCsv(results))}>Export CSV</button></div></>}
  </section>;
}
