import type { MicromouseComparison, MouseRealism } from '../maze/micromouse';
import type { MouseMotion } from '../maze/micromouseProfiles';
import { matchingMouseProfile } from '../maze/micromouseProfiles';
import type { GeneratorId, MazeTopology } from './maze';
import type { MicromouseBatchResult } from './micromouseBatch';

export type ComparisonExportContext=Readonly<{seed:number;width:number;height:number;generator:GeneratorId;topology:MazeTopology;format:string;motion:MouseMotion;realism:MouseRealism}>;

const columns=['seed','width','height','format','generator','topology','robot_profile','max_speed_mps','acceleration_mps2','traction_limit_mps2','effective_acceleration_mps2','turn_90_ms','sensor_range_cells','sensor_noise','correction_ms','collision_ms','diagonal_speed_runs','strategy','success','search_time_ms','search_cells','return_time_ms','speed_time_ms','total_time_ms','speed_cells','speed_distance_cells','diagonal_cuts','turns','revisits','explored_percent','speed_route_quality','collisions','reason'] as const;
const csvCell=(value:unknown)=>{const text=String(value??'');return /[",\r\n]/.test(text)?`"${text.replace(/"/g,'""')}"`:text;};
const csv=(rows:readonly Record<string,unknown>[])=>[columns.join(','),...rows.map(row=>columns.map(column=>csvCell(row[column])).join(','))].join('\r\n')+'\r\n';
const contextFields=(context:ComparisonExportContext)=>({width:context.width,height:context.height,format:context.format,generator:context.generator,topology:context.topology,robot_profile:matchingMouseProfile(context.motion),max_speed_mps:context.motion.maxSpeedMps,acceleration_mps2:context.motion.accelerationMps2,traction_limit_mps2:context.realism.tractionLimitMps2,effective_acceleration_mps2:Math.min(context.motion.accelerationMps2,context.realism.tractionLimitMps2),turn_90_ms:context.motion.turn90Ms,sensor_range_cells:context.realism.sensorRangeCells,sensor_noise:context.realism.sensorNoise,correction_ms:context.realism.correctionMs,collision_ms:context.realism.collisionMs,diagonal_speed_runs:context.realism.diagonalSpeedRuns});
const comparisonRow=(context:ComparisonExportContext,row:MicromouseComparison)=>({seed:context.seed,...contextFields(context),strategy:row.strategy,success:row.success,search_time_ms:row.metrics.search.timeMs,search_cells:row.metrics.search.cells,return_time_ms:row.metrics.return.timeMs,speed_time_ms:row.metrics.speed.timeMs,total_time_ms:row.metrics.totalTimeMs,speed_cells:row.metrics.speed.cells,speed_distance_cells:row.metrics.speedDistanceCells,diagonal_cuts:row.metrics.speedDiagonalCuts,turns:row.metrics.search.turns+row.metrics.return.turns+row.metrics.speed.turns,revisits:row.metrics.revisits,explored_percent:row.metrics.exploredPercent,speed_route_quality:row.metrics.speedRouteQuality,collisions:row.metrics.collisions,reason:''});

export function batchCsv(result:MicromouseBatchResult):string{const context={width:result.maze.width,height:result.maze.height,format:result.maze.format,generator:result.maze.generator,topology:result.maze.topology,robot_profile:result.robotProfile,max_speed_mps:result.motion.maxSpeedMps,acceleration_mps2:result.motion.accelerationMps2,traction_limit_mps2:result.realism.tractionLimitMps2,effective_acceleration_mps2:Math.min(result.motion.accelerationMps2,result.realism.tractionLimitMps2),turn_90_ms:result.motion.turn90Ms,sensor_range_cells:result.realism.sensorRangeCells,sensor_noise:result.realism.sensorNoise,correction_ms:result.realism.correctionMs,collision_ms:result.realism.collisionMs,diagonal_speed_runs:result.realism.diagonalSpeedRuns};return csv(result.runs.map(row=>({seed:row.seed,...context,effective_acceleration_mps2:row.effectiveAccelerationMps2,strategy:row.strategy,success:row.success,search_time_ms:row.searchTimeMs,search_cells:row.searchCells,return_time_ms:row.returnTimeMs,speed_time_ms:row.speedTimeMs,total_time_ms:row.totalTimeMs,speed_cells:row.speedCells,speed_distance_cells:row.speedDistanceCells,diagonal_cuts:row.speedDiagonalCuts,turns:row.turns,revisits:row.revisits,explored_percent:row.exploredPercent,speed_route_quality:row.speedRouteQuality,collisions:row.collisions,reason:row.reason??''})));}
export function batchJson(result:MicromouseBatchResult):string{return JSON.stringify({version:1,type:'micromouse-batch',...result},null,2)+'\n';}
export function comparisonCsv(rows:readonly MicromouseComparison[],context:ComparisonExportContext):string{return csv(rows.map(row=>comparisonRow(context,row)));}
export function comparisonJson(rows:readonly MicromouseComparison[],context:ComparisonExportContext):string{return JSON.stringify({version:1,type:'micromouse-strategy-comparison',context:{...context,robotProfile:matchingMouseProfile(context.motion)},results:rows.map(row=>comparisonRow(context,row))},null,2)+'\n';}

export function downloadText(filename:string,text:string,type:string):void{const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),0);}
export const exportFilename=(kind:'batch'|'comparison',extension:'csv'|'json')=>`infimaze-micromouse-${kind}.${extension}`;
